### ISSUE TITLE
Font for symbols?

### ISSUE THREAD

**Issue by eduo** [frippz/wasd-iso-sv-aek2#1]
Hi! You probably don't even remember this, but I was trying to make a variant of this for Spanish and I would much rather have the symbols in all modifiers.

I see you have some, but not all. Since the symbols are not in Univers, what font did you use for those?

**Comment by frippz** [comment]
Of course I remember! 😄 The problem is that I only modified [someone else's SVG](https://github.com/frippz/wasd-iso-sv-aek2#did-you-make-this-yourself) for my needs. Since this is based on the Apple Extended Keyboard II, your best bet would be to see if you could find someone that have vectorized all the symbols.
